version: '3.2'

services:

  drupal:
    build:
        context: .
        dockerfile: Dockerfile
    image: drupal-custom
    ports:
      - 80:80
    networks:
      - frontend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    volumes:
      - drupal-modules:/var/www/html/modules 
      - drupal-profiles:/var/www/html/profiles 
      - drupal-sites:/var/www/html/sites 
      - drupal-themes:/var/www/html/themes

  postgres:
    image: postgres
    networks: 
      - frontend
    secrets: 
      - psql_pass
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: kuasaipasswd

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  postgres-data:

networks:
  frontend:
    external: true
      name: frontend

secrets:
  psql_pass:
    file ./psql_pass.txt